### ISSUE TITLE
Packages that should be marked as research software

### ISSUE THREAD

**Issue by astrofrog** [Impactstory/depsy#10]
The following packages are marked as 'non-research' but should be research software:

http://depsy.org/package/python/FITS_tools
http://depsy.org/package/python/sdpy
http://depsy.org/package/python/APLpy
http://depsy.org/package/python/pvextractor
http://depsy.org/package/python/montage-wrapper
http://depsy.org/package/python/reproject
http://depsy.org/package/python/wcsaxes
http://depsy.org/package/python/Hyperion

Thanks for providing this service!

**Comment by bsipocz** [comment]
And these, too.

http://depsy.org/package/python/photutils
http://depsy.org/package/python/astroquery

**Comment by astrofrog** [comment]
This one too:

http://depsy.org/package/python/spectral-cube

**Comment by hpiwowar** [comment]
thanks!

**Comment by hpiwowar** [comment]
also pyspeckit

**Comment by astrofrog** [comment]
@hpiwowar - one idea to catch many of these is that a lot of them import astropy, and importing a research software package should probably increase the probability that the package using it is also research software.

**Comment by keflavich** [comment]
more from me:
https://pypi.python.org/pypi/pyradex
https://pypi.python.org/pypi/dust_emissivity
https://pypi.python.org/pypi/image_registration
https://pypi.python.org/pypi/musepy
https://pypi.python.org/pypi/scimes
https://pypi.python.org/pypi/plfit
https://pypi.python.org/pypi/specutils

**Comment by ethanwhite** [comment]
Adding one more:
http://depsy.org/package/python/retriever

**Comment by jasonpriem** [comment]
@astrofrog Good idea to look at imports to decide is_academic status! We looked at this and ended up deciding not to go this route, because we'd love to keep the is_academic dimension orthogonal to the dependency network information.

It's pretty cool to find a clearly non-academic package importing an academic one...for instance, lots of people use scipy for all kinds of non-sciencey things. Eventually we could distill this into some kind of Broader Impacts Index or something like that, which seems like it'd be fun and useful. We can't do that unless we decouple imports from researchyness. (For a similar reason we're not using any citation or publication information to determine if something is research software...we can learn cool things if we keep 'em decoupled).

That said, thinking about it does make one wonder what the definition of is_academic should even be. There's one way to look at it that, if you use such-and-such a library, by golly, that's academic enough for me. Or if you published a paper, or got cited, or are written by an academic, or lots of other approaches.

It really comes down to what we want to be saying when we say that a project is research software, and that's just not that well defined. We're taking one approach, but we'll keep listening and are certainly open to modifying how we look at it to match whatever the community is finding most useful.

**Comment by astrofrog** [comment]
@jasonpriem - thanks for the explanation, you are indeed right that the import information is not really enough. Just to confirm though, all the packages listed above are unambiguously research software, i.e. they were developed specifically for research.

**Comment by hpiwowar** [comment]
Fixed!  All the packages listed in this thread are now classified as research software in Depsy.  ([See code updates here.](https://github.com/Impactstory/depsy/commit/0d327ceffcd581ae5666d7fb8c3d9d2a58e85737) )

Thanks for taking the time to report these, and let us know if there are other we should fix!

ps The only exception is https://pypi.python.org/pypi/musepy, which isn't in Depsy because it was created after Jan 1 2015, and at the moment [we only include packages created before then](https://github.com/Impactstory/depsy-research/blob/master/introducing_depsy.md#limitations).

**Comment by hpiwowar** [comment]
@astrofrog yup agreed, all are research software and now should be fixed.  :)
