### ISSUE TITLE
Question: how to improve guessing (research software or not)?

### ISSUE THREAD

**Issue by pawamoy** [Impactstory/depsy#104]
Here are simple things I thought of to improve the guessing as research software, please tell us if they actually impact the guessing or not (and add the ones you know/thought of as well :smile:):

- Use the `Intended Audience :: Science/Research` PyPI classifier in `setup.py`.
-  Add `research`, `science`, `university` or other keywords in README.
-  Add those keywords in the `keywords` section of `setup.py`.
-  More generally, add those keywords anywhere in the documentation (including source code doc like docstrings).
-  Again, add those keywords in the tags (topics) of the GitHub repository.
-  Add citations, links to papers (articles) or bibliography in the documentation.
-  Have well-known university email addresses or university websites links.

*Note: I couldn't find any docs on how Depsy is guessing that, but maybe I missed something?*

**Comment by andim** [comment]
To give a concrete example depsy does not classify Noisyopt (https://github.com/andim/noisyopt) as research software http://depsy.org/package/python/noisyopt 

And this despite `Intended Audience :: Science/Research` tag on pypi and clearly scientific aim.

If anyone has an idea of what is going, let me know!

**Comment by Pawamoy** [comment]
Alright, I'm taking a look at the source code.

`Intended Audience :: Science/Research` classifier should work. If it's not the case (and we see that with your Noisyopt package), I suspect this line

```python
if package_obj.intended_audience == "Science/Research":
```

to return False because of a trailing new-line (maybe), or the `intended_audience` property to return None:

```python
try:
    pypi_classifiers = self.api_raw["info"]["classifiers"]
except KeyError:
    return None
```

I also see in the code that a list of 'sciency' keywords are used to tag a package as academic, see the list here: https://github.com/Impactstory/depsy/blob/master/models/academic.py#L29.

However, these keywords are tested against a truncation of the 100 first characters of the package description:

```python
self.summary = truncate(self.api_raw["info"]["description"])
```

They also are tested against the packtage's tags obtained through setup's keywords and classifiers information.

So here is the updated list of criteria:

- [x] `Intended Audience :: Science/Research` classifier: **YES**, should work but seems to be buggy.
- [x] Keywords in short description: **YES** , if keywords appear in the first 100 characters.
- [x] Keywords in `keywords` section of `setup.py`: **YES**.
- [x] Keywords in project name: **YES**.
- [ ] Keywords in README: **NO**.
- [ ] Keywords in long description: **NO**.
- [ ] Keywords in source code or documentation: **NO**.
- [ ] Keywords in GitHub repository's topics: **NO**.
- [ ] Citations / bibliography in the documentation: **NO**.
- [ ] University email addresses / links: **NO**.

The unchecked criteria could serve as a TODO-list :smile:

**Comment by pawamoy** [comment]
Closing because project is not maintained anymore.
