### ISSUE TITLE
Incorrect rendering of front page on mobile devices

### ISSUE THREAD

**Issue by HenrikBengtsson** [Impactstory/depsy#12]
FYI, http://depsy.org/ does not render properly on smartphones and tables.  The page is right truncated (with a white background) when you scroll.  'Developer tools' in Google Chrome will allow you to reproduce and troubleshoot this.

**Comment by jasonpriem** [comment]
Thanks! Yeah, we are an absolute mess on mobile right now...we took the very 2002-era, desktop-first approach in developing, wholly to save time and launch faster. This made sense for us since we still get around 90% of visitors from there at Impactstory, a similar project. 

So, while improved mobile experience is very much on the roadmap, it's not our chief priority right now alas.
