### ISSUE TITLE
depsy is great - thank you! Just to let you know badges stopped working

### ISSUE THREAD

**Issue by mattdowle** [Impactstory/depsy#83]
depsy is really great.  Massive thank you!

Just to let you know the badge links seem to have stopped working; e.g.,
http://depsy.org/api/package/cran/data.table/badge.svg

**Comment by hpiwowar** [comment]
Fixed!  :)  
Glad you like depsy.  That's really great to hear :)

Our badge provider has been really slow today, so we stubbed them out while we got a better fix working because it was sinking our site :(.  
We'll now return an "unknown" badge when they really slow, but hopefully it won't happen again.

Thanks for reporting it!

Cheers, 
Heather

**Comment by mattdowle** [comment]
@hpiwowar  Wow - that was quick.  Thanks!  Yes working great again now.

**Comment by jasonpriem** [comment]
Nicely done, pardner 👍
